### ISSUE TITLE
mavsdk subprocess 

### ISSUE THREAD

**Issue by arnaudjuin** [alireza787b/mavsdk_drone_show#7]
Hello ! Thanks for your work it's genuiely fantastic. 
Though, I'm facing this problem on ubuntu virtual machine : 
![Uploading image.png…]()

Any idea what I should do to fix that ? 

Many thanks

**Comment by arnaudjuin** [comment]
<img width="746" alt="image" src="https://github.com/alireza787b/mavsdk_drone_show/assets/36408241/68234e23-8d73-4ec1-a314-6e278ef9517b">

**Comment by alireza787b** [comment]
Hello, and thanks for the kind words! 

Regarding the issue you're encountering, it seems like it could be related to the `mavsdk_server` binary. Here's a breakdown of some steps you can take to troubleshoot:

1. **Directory Path**: First off, the path to the repo seems a bit long. Try moving the project to your home directory with `cd ~`. Believe it or not, long directory paths can sometimes cause unexpected issues.

2. **Binary Source**: As for the `mavsdk_server` binary, did you download it directly from MAVSDK or build it yourself? Ensure you have the correct version and that it's placed in the appropriate folder within the project.

3. **Manual Execution**: To get more insights, you can run `mavsdk_server` manually. Open a terminal, navigate to the directory where the binary is located, and execute:
`    ./mavsdk_server -p 50051
`    The `-p 50051` flag specifies the port for the gRPC server. Feel free to change `50051` to another port if needed. If the server starts successfully, you'll see logs indicating it's ready to accept connections. Any error messages can provide clues for troubleshooting.

4. **File Integrity and Permissions**: It's also worth checking if the file might be corrupted or if there are permission issues. Run `ls -l ./mavsdk_server` to check permissions, and if needed, make it executable with `chmod +x ./mavsdk_server`.

By following these steps, you should be able to pinpoint the issue. If you still encounter problems, please share the output, and we can dig deeper.

Hope this helps, and I'm looking forward to hearing how it goes!

**Comment by arnaudjuin** [comment]
Thanks for your quick answer ! 

Unfortunately, I followed those steps but I still encounter the same issue. More insight : 

<img width="1153" alt="image" src="https://github.com/alireza787b/mavsdk_drone_show/assets/36408241/998b70a5-c9ff-4124-ae7d-48e9adffcd8e">

Thanks for your help.

**Comment by alireza787b** [comment]
Hello,

It seems like you're trying to run the mavsdk_server binary on an M1 Mac using Parallels and Ubuntu. The "cannot execute binary file: Exec format error" typically occurs when you're trying to run a binary compiled for a different architecture than the one you're currently using. In this case, the binary might have been compiled for a different architecture (like x86), and you're trying to run it on an ARM architecture (which the M1 chip uses).

To resolve this issue, you could try the following steps:

Check the architecture of the binary: You can use the file command to check the architecture of the binary. Run file mavsdk_server and check the output. It should tell you the architecture the binary was compiled for.

Check your system's architecture: You can check your system's architecture by running uname -m. This will tell you the architecture of your current system.

Match the architectures: Make sure the architecture of the binary matches the architecture of your system. If they don't match, you'll need to get a version of the binary that is compiled for your system's architecture.

Recompile the binary: If you have access to the source code and the necessary build tools, you could try recompiling the binary on your own machine. This should produce a binary that is compatible with your system's architecture.

Please let me know if this helps or if you need further assistance.

Best regards,

**Comment by arnaudjuin** [comment]
Problem solved by copying the binary installed by pip in your repo. Many thanks !

**Comment by arnaudjuin** [comment]
Much appreciated.
