### ISSUE TITLE
Decoding problem

### ISSUE THREAD

**Issue by arnaudjuin** [alireza787b/mavsdk_drone_show#9]
An other issue I am encountering with the flask server : 

<img width="1397" alt="image" src="https://github.com/alireza787b/mavsdk_drone_show/assets/36408241/035c9ec4-743f-4c36-a873-aeef9e545a58">

My config is the following : 
hw_id,pos_id,x,y,ip,mavlink_port,debug_port,gcs_ip
1,1,-1.5,-1.5,127.0.0.1,14551,14550,172.17.0.1

What do you think ? I am not sure I am using the right ports. What is the difference between the mavlink port and the debug ? How can I find those in Qgroundcontrol or Jmavsim?

Many thanks. 

Arnaud

**Comment by alireza787b** [comment]
usually default would work. depends on which verison you are using. 
debug port is the port for custom telemetry. mavlink for the qground. but from version 0.7 I used same shared mavlink port so all drones talk on UDP 14550 (or 24550,34550 refer to documentation) to the ground station. you don't need to change anyof settings in your sim. eveything should work by default. to only place you need to change is Qgroundcontrol conneciton
